# Generated by Django 4.1 on 2022-09-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', 'Added_slug _To_product_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.IntegerField(null=True, max_length=5),
            preserve_default=False,
        ),
    ]
